### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by mvalbuquerque** [dbonates/EasyBalance-App#1]
/Users/Vinicius/Downloads/EasyBalance-App-master/Pods/Headers/Public/SSKeychain/SSKeychainQuery.h
/Users/Vinicius/Downloads/EasyBalance-App-master/Pods/Headers/Public/SSKeychain/SSKeychainQuery.h:9:1: Use of '@import' when modules are disabled
/Users/Vinicius/Downloads/EasyBalance-App-master/Pods/Headers/Public/SSKeychain/SSKeychainQuery.h:10:1: Use of '@import' when modules are disabled

**Comment by dbonates** [comment]
fixed, and the app is back on trails on App Store 😉
